### 각각의 데이터셋 불러오기

In [6]:
import pandas as pd
df1_train = pd.read_csv('1.옥외누수(out-training).csv')
df2_train = pd.read_csv('2.옥내누수(in-training).csv')
df3_train = pd.read_csv('3.기계.전기음(noise-training).csv')
df4_train = pd.read_csv('4.환경음(other-training).csv')
df5_train = pd.read_csv('5.정상음(normal-training).csv')

df1_valid = pd.read_csv('1.옥외누수(out-validation).csv')
df2_valid = pd.read_csv('2.옥내누수(in-validation).csv')
df3_valid = pd.read_csv('3.기계.전기음(noise-validation).csv')
df4_valid = pd.read_csv('4.환경음(other-validation).csv')
df5_valid = pd.read_csv('5.정상음(normal-validation).csv')

### df_train, df_valid 하나로 만들기

In [8]:
 df_train = pd.concat([df1_train, df2_train, df3_train, df4_train, df5_train], ignore_index=True)

In [9]:
 df_valid = pd.concat([df1_valid, df2_valid, df3_valid, df4_valid, df5_valid], ignore_index=True)

### 데이터셋 요약 및 모양 확인

In [11]:
df_train.describe()

,ldate,lrate,llevel,0HZ,10HZ,20HZ,30HZ,40HZ,50HZ,60HZ,...,MAX10,MAX11,MAX12,MAX13,MAX14,MAX15,MAX16,MAX17,MAX18,MAX19
count,6.256400e+04,62564.000000,62564.000000,62564.0,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,...,62564.00000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000,62564.000000
mean,2.020076e+07,75.931526,447.207228,0.0,5.305719,5.583562,5.943482,6.340084,6.768062,11.076642,...,511.05492,413.370804,505.911547,413.052426,506.957356,412.666709,513.520235,413.740873,511.642958,411.035420
std,5.816738e+03,22.210028,240.240117,0.0,5.699169,6.325584,7.180028,8.261700,9.520785,53.026483,...,821.25583,285.865414,808.999371,286.484312,810.835384,286.436706,824.983970,287.399663,819.483059,287.275671
min,2.019023e+07,30.000000,112.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,30.00000,9.000000,30.000000,9.000000,30.000000,9.000000,30.000000,9.000000,30.000000,9.000000
25%,2.020042e+07,60.000000,239.000000,0.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,260.00000,168.000000,260.000000,167.000000,260.000000,167.000000,260.000000,166.000000,260.000000,166.000000
50%,2.020080e+07,90.000000,400.000000,0.0,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,310.00000,366.000000,310.000000,366.000000,310.000000,366.000000,310.000000,368.000000,310.000000,363.000000
75%,2.020120e+07,90.000000,615.000000,0.0,5.000000,5.000000,6.000000,6.000000,6.000000,7.000000,...,380.00000,612.000000,380.000000,612.000000,380.000000,614.000000,390.000000,616.000000,390.000000,612.000000
max,2.021021e+07,90.000000,1650.000000,0.0,83.000000,146.000000,125.000000,196.000000,322.000000,1221.000000,...,4990.00000,1656.000000,5000.000000,1723.000000,5000.000000,1698.000000,5000.000000,1717.000000,5000.000000,1710.000000

In [12]:
df_valid.describe()

,ldate,lrate,llevel,0HZ,10HZ,20HZ,30HZ,40HZ,50HZ,60HZ,...,MAX10,MAX11,MAX12,MAX13,MAX14,MAX15,MAX16,MAX17,MAX18,MAX19
count,7.820000e+03,7820.000000,7820.000000,7820.0,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,...,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000,7820.000000
mean,2.020083e+07,75.863171,447.030179,0.0,5.247698,5.528261,5.906394,6.332353,6.733376,11.602046,...,485.382353,413.099488,493.933504,413.686701,498.338875,412.938875,491.489770,415.876982,492.290281,409.882864
std,5.829328e+03,22.294732,240.859505,0.0,5.607798,6.262665,7.329348,8.633944,9.368438,57.834773,...,765.821128,288.808763,785.757752,287.101538,793.154650,286.600692,773.490447,288.879362,782.852589,287.219533
min,2.019030e+07,30.000000,125.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,30.000000,10.000000,30.000000,10.000000,40.000000,10.000000,30.000000,10.000000,40.000000,10.000000
25%,2.020043e+07,60.000000,238.750000,0.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,260.000000,164.000000,260.000000,169.000000,260.000000,170.000000,260.000000,167.000000,260.000000,164.000000
50%,2.020073e+07,90.000000,399.000000,0.0,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,310.000000,364.000000,310.000000,365.500000,310.000000,364.000000,310.000000,365.000000,310.000000,361.000000
75%,2.020121e+07,90.000000,617.000000,0.0,5.000000,5.000000,6.000000,6.000000,6.000000,7.000000,...,380.000000,613.000000,380.000000,613.000000,380.000000,610.000000,380.000000,618.000000,380.000000,614.250000
max,2.021021e+07,90.000000,1653.000000,0.0,74.000000,84.000000,119.000000,218.000000,201.000000,1215.000000,...,4920.000000,1659.000000,4950.000000,1672.000000,4990.000000,1679.000000,5000.000000,1607.000000,4990.000000,1626.000000

In [14]:
print(df_train.shape)
print(df_valid.shape)

(62564, 539)
(7820, 539)